/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as GatedRouteImport } from './routes/_gated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as GatedWebsitesRouteImport } from './routes/_gated/websites'
import { Route as GatedSpreadsheetsRouteImport } from './routes/_gated/spreadsheets'
import { Route as GatedRemindersRouteImport } from './routes/_gated/reminders'
import { Route as GatedPremiumRouteImport } from './routes/_gated/premium'
import { Route as GatedGeneralCredentialsRouteImport } from './routes/_gated/general-credentials'
import { Route as GatedDashboardRouteImport } from './routes/_gated/dashboard'
import { Route as GatedAuditRouteImport } from './routes/_gated/audit'
import { Route as GatedWebsitesIdRouteImport } from './routes/_gated/websites.$id'

const GatedRoute = GatedRouteImport.update({
  id: '/_gated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const GatedWebsitesRoute = GatedWebsitesRouteImport.update({
  id: '/websites',
  path: '/websites',
  getParentRoute: () => GatedRoute,
} as any)
const GatedSpreadsheetsRoute = GatedSpreadsheetsRouteImport.update({
  id: '/spreadsheets',
  path: '/spreadsheets',
  getParentRoute: () => GatedRoute,
} as any)
const GatedRemindersRoute = GatedRemindersRouteImport.update({
  id: '/reminders',
  path: '/reminders',
  getParentRoute: () => GatedRoute,
} as any)
const GatedPremiumRoute = GatedPremiumRouteImport.update({
  id: '/premium',
  path: '/premium',
  getParentRoute: () => GatedRoute,
} as any)
const GatedGeneralCredentialsRoute = GatedGeneralCredentialsRouteImport.update({
  id: '/general-credentials',
  path: '/general-credentials',
  getParentRoute: () => GatedRoute,
} as any)
const GatedDashboardRoute = GatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => GatedRoute,
} as any)
const GatedAuditRoute = GatedAuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => GatedRoute,
} as any)
const GatedWebsitesIdRoute = GatedWebsitesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => GatedWebsitesRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/audit': typeof GatedAuditRoute
  '/dashboard': typeof GatedDashboardRoute
  '/general-credentials': typeof GatedGeneralCredentialsRoute
  '/premium': typeof GatedPremiumRoute
  '/reminders': typeof GatedRemindersRoute
  '/spreadsheets': typeof GatedSpreadsheetsRoute
  '/websites': typeof GatedWebsitesRouteWithChildren
  '/websites/$id': typeof GatedWebsitesIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/audit': typeof GatedAuditRoute
  '/dashboard': typeof GatedDashboardRoute
  '/general-credentials': typeof GatedGeneralCredentialsRoute
  '/premium': typeof GatedPremiumRoute
  '/reminders': typeof GatedRemindersRoute
  '/spreadsheets': typeof GatedSpreadsheetsRoute
  '/websites': typeof GatedWebsitesRouteWithChildren
  '/websites/$id': typeof GatedWebsitesIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_gated': typeof GatedRouteWithChildren
  '/_gated/audit': typeof GatedAuditRoute
  '/_gated/dashboard': typeof GatedDashboardRoute
  '/_gated/general-credentials': typeof GatedGeneralCredentialsRoute
  '/_gated/premium': typeof GatedPremiumRoute
  '/_gated/reminders': typeof GatedRemindersRoute
  '/_gated/spreadsheets': typeof GatedSpreadsheetsRoute
  '/_gated/websites': typeof GatedWebsitesRouteWithChildren
  '/_gated/websites/$id': typeof GatedWebsitesIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/audit'
    | '/dashboard'
    | '/general-credentials'
    | '/premium'
    | '/reminders'
    | '/spreadsheets'
    | '/websites'
    | '/websites/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/audit'
    | '/dashboard'
    | '/general-credentials'
    | '/premium'
    | '/reminders'
    | '/spreadsheets'
    | '/websites'
    | '/websites/$id'
  id:
    | '__root__'
    | '/'
    | '/_gated'
    | '/_gated/audit'
    | '/_gated/dashboard'
    | '/_gated/general-credentials'
    | '/_gated/premium'
    | '/_gated/reminders'
    | '/_gated/spreadsheets'
    | '/_gated/websites'
    | '/_gated/websites/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  GatedRoute: typeof GatedRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_gated': {
      id: '/_gated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof GatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_gated/websites': {
      id: '/_gated/websites'
      path: '/websites'
      fullPath: '/websites'
      preLoaderRoute: typeof GatedWebsitesRouteImport
      parentRoute: typeof GatedRoute
    }
    '/_gated/spreadsheets': {
      id: '/_gated/spreadsheets'
      path: '/spreadsheets'
      fullPath: '/spreadsheets'
      preLoaderRoute: typeof GatedSpreadsheetsRouteImport
      parentRoute: typeof GatedRoute
    }
    '/_gated/reminders': {
      id: '/_gated/reminders'
      path: '/reminders'
      fullPath: '/reminders'
      preLoaderRoute: typeof GatedRemindersRouteImport
      parentRoute: typeof GatedRoute
    }
    '/_gated/premium': {
      id: '/_gated/premium'
      path: '/premium'
      fullPath: '/premium'
      preLoaderRoute: typeof GatedPremiumRouteImport
      parentRoute: typeof GatedRoute
    }
    '/_gated/general-credentials': {
      id: '/_gated/general-credentials'
      path: '/general-credentials'
      fullPath: '/general-credentials'
      preLoaderRoute: typeof GatedGeneralCredentialsRouteImport
      parentRoute: typeof GatedRoute
    }
    '/_gated/dashboard': {
      id: '/_gated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof GatedDashboardRouteImport
      parentRoute: typeof GatedRoute
    }
    '/_gated/audit': {
      id: '/_gated/audit'
      path: '/audit'
      fullPath: '/audit'
      preLoaderRoute: typeof GatedAuditRouteImport
      parentRoute: typeof GatedRoute
    }
    '/_gated/websites/$id': {
      id: '/_gated/websites/$id'
      path: '/$id'
      fullPath: '/websites/$id'
      preLoaderRoute: typeof GatedWebsitesIdRouteImport
      parentRoute: typeof GatedWebsitesRoute
    }
  }
}

interface GatedWebsitesRouteChildren {
  GatedWebsitesIdRoute: typeof GatedWebsitesIdRoute
}

const GatedWebsitesRouteChildren: GatedWebsitesRouteChildren = {
  GatedWebsitesIdRoute: GatedWebsitesIdRoute,
}

const GatedWebsitesRouteWithChildren = GatedWebsitesRoute._addFileChildren(
  GatedWebsitesRouteChildren,
)

interface GatedRouteChildren {
  GatedAuditRoute: typeof GatedAuditRoute
  GatedDashboardRoute: typeof GatedDashboardRoute
  GatedGeneralCredentialsRoute: typeof GatedGeneralCredentialsRoute
  GatedPremiumRoute: typeof GatedPremiumRoute
  GatedRemindersRoute: typeof GatedRemindersRoute
  GatedSpreadsheetsRoute: typeof GatedSpreadsheetsRoute
  GatedWebsitesRoute: typeof GatedWebsitesRouteWithChildren
}

const GatedRouteChildren: GatedRouteChildren = {
  GatedAuditRoute: GatedAuditRoute,
  GatedDashboardRoute: GatedDashboardRoute,
  GatedGeneralCredentialsRoute: GatedGeneralCredentialsRoute,
  GatedPremiumRoute: GatedPremiumRoute,
  GatedRemindersRoute: GatedRemindersRoute,
  GatedSpreadsheetsRoute: GatedSpreadsheetsRoute,
  GatedWebsitesRoute: GatedWebsitesRouteWithChildren,
}

const GatedRouteWithChildren = GatedRoute._addFileChildren(GatedRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  GatedRoute: GatedRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
